### ISSUE TITLE
Email addresses are lost after a few logins

### ISSUE THREAD

**Issue by dydx** [neo4jrb/devise-neo4j#19]
Running through the example code, I'm getting a strange condition where the "email" property is reverting to empty after a few logins.

I took a screencap of this happening, as its a little hard to explain:

https://www.youtube.com/watch?v=qI_ep7Ffx58

Any insights? I'd really like to use Devise and Neo4j in a service I'm working on

**Comment by dydx** [comment]
Here's a bit of output from `rails s`:

````
Started POST "/users" for 192.168.1.231 at 2015-09-11 00:13:41 -0400
Cannot render console from 192.168.1.231! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Devise::RegistrationsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"8YROSHNbQqEpjRGAohUxuBkKTZx1MPi3GKW5YUoMXBnMpai0QEhRErxb0q9UB24MBQHVUBcYVyD30MVjz1b5aA==", "user"=>{"email"=>"test@example.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Sign up"}
 CYPHER 106ms MATCH (result:`User`) WHERE (result.email = {result_email}) RETURN COUNT(result) AS count | {:result_email=>"test@example.com"}
 CYPHER 24ms CREATE (n:`User` {props}) RETURN ID(n) | {:props=>{:uuid=>"3d2da633-d3bc-4bf6-8f03-439c4002e56a", :created_at=>1441944821, :updated_at=>1441944821, :email=>"test@example.com", :encrypted_password=>"$2a$10$ekMmxy/5l9YPR96HuaMZWersCgZl.ANxzzd4Jx55x9v3YM3AJ.zIe", :sign_in_count=>0}}
 CYPHER 96ms MATCH n WHERE (ID(n) = {ID_n}) WITH n RETURN ID(n) | {:ID_n=>0}
 CYPHER 25ms MATCH n WHERE (ID(n) = {ID_n}) WITH n SET n.`updated_at` = {setter_n_updated_at}, n.`sign_in_count` = {setter_n_sign_in_count}, n.`current_sign_in_at` = {setter_n_current_sign_in_at}, n.`last_sign_in_at` = {setter_n_last_sign_in_at}, n.`current_sign_in_ip` = {setter_n_current_sign_in_ip}, n.`last_sign_in_ip` = {setter_n_last_sign_in_ip}, n.`email` = {setter_n_email} | {:ID_n=>0, :setter_n_updated_at=>1441944821, :setter_n_sign_in_count=>1, :setter_n_current_sign_in_at=>1441944821, :setter_n_last_sign_in_at=>1441944821, :setter_n_current_sign_in_ip=>"192.168.1.231", :setter_n_last_sign_in_ip=>"192.168.1.231", :setter_n_email=>""}
Redirected to http://192.168.1.97:3000/
Completed 302 Found in 540ms

````

It looks sort of like there's a problem in "trackable" that is causing the value to turn to "". I noticed that when looking at the Neo4j admin that the login counter never increments.

**Comment by dydx** [comment]
I can remove the `:trackable` property at the end of `app/models/user.rb` in the `devise` section, and everything works fine.

It looks like whatever `trackable` is doing, its trying to update the email address or something and failing. I'll try and see if I can come up with a patch to get the `trackable` functionality working again.

**Comment by subvertallchris** [comment]
What versions of the Neo4j gem and Devise are you using? Can you try
removing the `type` option from the `email` property in your User model of
it's set?

**Comment by subvertallchris** [comment]
"...in your User model _if_ it's set," I meant to say.

**Comment by dydx** [comment]
I'm using Neo4j 2.2.5, Neo4jrb 5.2.4, and devise-neo4j 2.0.0 (ref master on Github).

The `type` is set to `String` in the `user` model; I removed that and added the `:trackable` stuff and I get the same result; the email is being reverted to "" for some reason

**Comment by subvertallchris** [comment]
Ok, just making sure. I encountered a weird bug related to String types and
wanted to be sure this wasn't it.

Let us know if you need any help digging into trackable. I'm not too
familiar with Devise's internals but will help however I can. I'll be
online all day tomorrow, pop into the Gitter room if you want.

**Comment by dydx** [comment]
Yeah definitely.

**Comment by jbhannah** [comment]
+1, same versions of Neo4j, Neo4jrb, and devise-neo4j as @dydx, on Ruby 2.2.2 (gotta upgrade to 2.2.3) and Rails 4.2.4. Disabling `:trackable` also fixed it for me. Available to test fixes and help dig into what's going on here if necessary.

**Comment by dydx** [comment]
Something that came up in Gitter is removing the `default` setting on the email property; it seems to behave well under those conditions. Not really sure why, though.

As was also mentioned in Gitter, having a real validator is a lot better than running through a default empty string on something important like the email field.

Code works now on everything from `5.1.5` to `master`, at least on my end. 

@jbhannah

**Comment by jbhannah** [comment]
Thanks @dydx, I'll give that a try this evening.

**Comment by subvertallchris** [comment]
I released 5.2.5 this morning, see if that takes care of it?

**Comment by dydx** [comment]
That does the trick!

**Comment by jbhannah** [comment]
Yup, Neo4jrb 5.2.5 fixes this.

**Comment by dydx** [comment]
I think its relatively safe to say this is fixed. Closing the issue.

**Comment by subvertallchris** [comment]
Great, thanks for the troubleshooting help and quick follow ups. Very happy
to have caught this so soon after the buggy release!
