### ISSUE TITLE
Does devise-neo4j support token authentication

### ISSUE THREAD

**Issue by spinlock99** [neo4jrb/devise-neo4j#22]
Hi. 

I'm looking to use neo4j as a database for a rails api and I'll need to use token authentication to support an SPA front-end. Does `devise-neo4j` support token authentication? I know it's been removed from `devise` for quite some time and I'm just wondering if `devise-neo4j` has added it back in.

Thanks!

**Comment by subvertallchris** [comment]
This gem only provides some methods for compatibility between Neo4j.rb and
Devise, so you'll find no new features or changed behavior here. From what
I remember, Devise removed their native token auth support but there are
some blog posts explaining how to hack it back in.

**Comment by spinlock99** [comment]
Thanks @subvertallchris. That's what I figured but just wanted to check and make sure.
