### ISSUE TITLE
Gemfile.lock tied to rails 4.2.3 in Windows

### ISSUE THREAD

**Issue by mcr431** [neo4jrb/devise-neo4j#30]
In the Gemfile.lock it specifies version 4.2.3 for all rails gems. I'm using rails 5 and have no idea if i can fix this. Not sure if I can change it to accept rails 5. Has anyone else noticed this and is there an active fix? I don't want to change stuff and break a ton of things.

**Comment by mcr431** [comment]
Additionally the gemspec file contains these three lines:

``` s.files         = `git ls-files`.split("\n")
s.test_files    = `git ls-files -- test/*`.split("\n")
s.executables   = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }```

Which end up throwing 3 fatal git errors whenever I try to rake since it is not recognizing a git directory. Should I be cloning the repo and then installing and this will solve some of my issues?

**Comment by cheerfulstoic** [comment]
If you want to update rails I believe you can just do `bundle update rails` and it will calculate the dependencies of your various gems, install the Rails 5 gems, and update your `Gemfile.lock` accordingly.

Regarding the `.gemspec`, I don't believe I understand.  Do you mean it's not recognizing the `git` command?  If so it sounds like you might have a path issue from your install of `git`.  You might try going into Ruby and running something like `git log` to try to figure out the issue.  I don't know how it would work on Windows, but you might be able to also run shell commands inside Ruby to get the list of your paths.

Also, if you have a new enough version of Windows I'd suggest using the new built-in bash environment:

https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

**Comment by mcr431** [comment]
Thank you for the quick response! I'll try that when I get home from work and see if I'm still having problems.

**Comment by mcr431** [comment]
The ```bundle update rails``` didn't work but I ended up just deleting the ```gemfile.lock``` and installing the dependencies manually. And to solve the git errors I had to initialize a repo somewhere in the parent path of ```devise-neo4j```.

Everything seems to be working now.
