### ISSUE TITLE
Issue with the versions of oauth2

### ISSUE THREAD

**Issue by rubymaniac** [neo4jrb/devise-neo4j#6]
I am trying to install devise-neo4j with devise and the omniauth (used by devise omniauthable) but with no result because there is an incompatibility between the devise-neo4j's oauth2 dependency and the omniauth-facebook's oauth2 dependency. The devise-neo4j depends on oauth2(0.4.1) and the omniauth-facebook gem depends on omniauth(~> 0.5.0). Can you update your dependencies?

**Comment by subvertallchris** [comment]
Closing this out due to age. If anyone else runs into this, please start a new issue.
